### ISSUE TITLE
Consolidate versions of CritCat charge

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-mig/critcat#14]
# tasks

- [ ] Approve charge [working document](https://docs.google.com/document/d/1Jax-JEI4Pf7OoTId2OSrUQtGh9Em1aHxG8aRitra0To/edit?usp=sharing) in Google Shared Drive
- [ ] Publish finalized charge [in Staffweb](https://staff.lib.uw.edu/groups/critcat/about/charge), in this repository's [README](https://github.com/uwlib-mig/critcat#group-charge)

# background

At time of writing there are three _slightly different_ CritCat 'charge' documents:

1. Staffweb > ... > [Charge](https://staff.lib.uw.edu/groups/critcat/about/charge)\*
   - Has bullet points, only minor differences with 2
2. CritCat Shared Drive > ... > [Critical Cataloging, Archival Description, and Metadata Working Group (CritCat) charge](https://docs.google.com/document/d/1Jax-JEI4Pf7OoTId2OSrUQtGh9Em1aHxG8aRitra0To/edit?usp=sharing)\*
   - Has bullet points, only minor differences with 1
3. uwlib-mig/critcat/README > [Group Charge](https://github.com/uwlib-mig/critcat#group-charge)
   - No bullets

\* *UW NetID access only*

📢 PROPOSAL
- Use doc in the Shared Drive (2) as the working and source document 
   - Finalize and approve charge there
   - Publish finalized version at location 1 and 3
   - Add information to Shared Drive (2) providing URLs where it is published

**Comment by ElaineSpeer** [comment]
Sounds good to me, I don't think I have anything to add

**Comment by CECSpecialistI** [comment]
I'm supportive of one charge published in one place! Thanks Benjamin!

**Comment by weirdbananakat** [comment]
Ditto!

From: Crystal Yragui (Clements) ***@***.***>
Date: Wednesday, January 17, 2024 at 2:45 PM
To: uwlib-mig/critcat ***@***.***>
Cc: Kat Lewis ***@***.***>, Assign ***@***.***>
Subject: Re: [uwlib-mig/critcat] Consolidate versions of CritCat charge (Issue #14)

I'm supportive of one charge published in one place! Thanks Benjamin!

**Comment by smfitch** [comment]
I also am supportive of one charge published in one place.

**Comment by briesenberg07** [comment]
Can this be closed?

**Comment by smfitch** [comment]
yes
