### ISSUE TITLE
publish harriman project resources

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-mig/critcat#2]
# PUBLISH HARRIMAN PROJECT SUMMARY AND DATA

- directory critcat/harriman
   - README.md, including:
      - [Project scope](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_mig/Shared%20Documents/mig_projects/2023_harmful_language_remediation_pilot/resources.docx?d=w577a9c95e8de4f368f3fc12d5bb64b07&csf=1&web=1&e=CWiSXN&nav=eyJoIjoiOTI4NzM2OTI1In0)
      - Link to collection landing page
      - Link to [harriman metadata application profile](https://uwlib-mig.github.io/contentdm_maps/html/harriman.html)
      - Guide to data included in project directory (`.csv` file below, possibly other files...)
      - ...?
   -  harriman_target_records.csv (export from [og_library_mig Excel file](https://uwnetid.sharepoint.com/:x:/r/sites/og_library_mig/Shared%20Documents/mig_projects/2023_harmful_language_remediation_pilot/harriman_target_records.xlsx?d=wabd1424f172a46de8224eb0a7b1469f8&csf=1&web=1&e=1bzzRH)) -- change history for CONTENTdm metadata
   - ...?

## 📜 NOTES
- No one outside repo contributors will be able to view this information ^^^ as long as uwlib-mig/critcat is a private repository
- We also changed EAD data and MARC data—not included in the proposal above--will we publish these changes as well?

Requesting feedback from @CECSpecialistI @ElaineSpeer @smfitch @weirdbananakat , will share as email for feedback from pilot project group members without GitHub accounts

**Comment by briesenberg07** [comment]
📢  ***Bare-minimum added to Past_Projects/Harriman/[README.md](https://github.com/uwlib-mig/critcat/tree/main/Past_Projects/Harriman#readme)***

DETAILS/NOTES:
- Includes working spreadsheet
- The 'before' and 'after' CONTENT commits were created by me from a single export --
   - I didn't get a 'before' export! 
   - So, I created a this from data in working spreadsheet (❗ TO DO for future projects - get 'before' exports for all metadata formats where changes will be made and we wish to record change history!)
- No EAD exports at this time - tagging @ElaineSpeer 
   - I imagine that a current/'after' EAD export can be made, but not sure whether previous versions are available for export, and if not, whether it's feasible or desirable to create this file as I did for the CONTENTdm XML

**Comment by ElaineSpeer** [comment]
Benjamin- versioning EAD may be a longer conversation, let me know if you want to schedule something. The short version is that I'm still in the process of figuring out how Mark set up our XML stuff so I don't think we have access to prior versions, but sometimes we find stuff so it's not impossible. The other thing is I don't remember how much the Alliance keeps as backups so I can reach out to them and see.

**Comment by briesenberg07** [comment]
Thanks @ElaineSpeer -- you mention:

> I don't remember how much the Alliance keeps as backups so I can reach out to them and see

Would you be willing to reach out to the Alliance and see if a previous version ('before') XML/EAD is available? If **yes**, we can store that, and, once your ability to export the current ('after') version of XML/EAD is sorted, we can store this as well (RELATED: [questions about CritCat data management](https://docs.google.com/document/d/1SogR6PjxRJZVM7zgiFeJhuH8mu6DYNBmPh1RWhJX0pc/edit#bookmark=id.44tn13yigq4n))? 

If **no**, maybe we don't have access to before/after EAD data for the pilot project. If that's the case, well, lessons will have been learned and we'll be sure to get a 'before' export next time!

*It should be noted ✏️ how **little** I understand the Encoded Archival Description standard. I believe it is XML-encoded data, so my general idea is to store versions of an EAD file in much the same way that I'm proposing we store CONTENTdm XML exports to create a record/view of updates made during remediation. Let's discuss more on the 23rd?*

**Comment by ElaineSpeer** [comment]
@briesenberg07 Yes, I think adding this to the agenda for the 23rd makes a lot of sense. I'll see what info I can gather before then.
