### ISSUE TITLE
Collection landing page changes complete

### ISSUE THREAD

**Issue by weirdbananakat** [uwlib-mig/critcat#7]
CONTENTdm collection langing pages

- Check landing pages or the collection and any pages that are linked to/from that landing page that may need remediation
- Request necessary changes

**Comment by ElaineSpeer** [comment]
There are 5 instances of the term on this page: https://content.lib.washington.edu/aipnw/frey.html
and 1 instance on this page: https://content.lib.washington.edu/aipnw/aip-overview.html 
I think we need to take a look at them, but it may be part of a larger conversation about the role of updating past project pages on CDM

**Comment by weirdbananakat** [comment]
I am going to pass these on to Ann L with the vocab update--I'll ask she addresses ASAP. 
I ~think~ she is the person that edits these pages. 
Kat

**Comment by ElaineSpeer** [comment]
@weirdbananakat here are the proposed changes for this page: https://content.lib.washington.edu/aipnw/frey.html can you please pass along to Anne Graham? Thanks!
" "For the Coeur d' Alene, who call themselves the Schitsu'umsh, literally meaning, "the ones that were found here", and often [pronounced Skitswish by neighboring tribes], they were [forcibly relocated to] what would become the Panhandle region of Idaho. It was a landscape of some 4,000,000 acres of fir, ponderosa and cedar-forested mountains, freshwater rivers, lakes and marshlands, and white pine and perennial bunchgrass and fescue wheatgrass-covered rolling hills and prairie. “
…

Glossary

Schitsu'umsh - literally meaning, "the ones that were found here," and often [pronounced Skitswish by neighboring tribes], referring to the Coeur d'Alene people"
