### ISSUE TITLE
Copy-negative database changes complete

### ISSUE THREAD

**Issue by weirdbananakat** [uwlib-mig/critcat#9]
Copy-negative database

- Edit individual descriptions of photos in the database to correspond with updated metadata

**Comment by CECSpecialistI** [comment]
Hooray! Thanks Elaine. I just learned what the copy-negative database was last week, so I appreciate you taking the lead on it :)

**Comment by ElaineSpeer** [comment]
The images do have copy negative numbers, but I have confirmed with Susan that these are not part of our negative database. Most likely they are from the NWMA- so this should be covered when we write to them about the update
